### PR TITLE
Add files for FixMissingStreamerInfos service

### PR DESCRIPTION
**Pull request by wddgit**
The new files are needed for cms-sw/cmssw#43175. See that PR for detailed comments. This should be merged first or at the same time as the that PR.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

This test doesn't really accomplish anything, just getting the box checked. The related CMSSW PR is the one that really tests these new files.

**Comment by makortel** [comment]
+core

**Comment by smuzaffar** [comment]
+externals

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
